### PR TITLE
Use HikariCP to Manage JDBC Pool

### PR DESCRIPTION
**Pull request by PseudoResonance**
I haven't been able to fully test this yet and verify that it resolves the issue #13, but it still connects to the server and likely doesn't pose any problems. I will see tomorrow if the issue has shown up again once the connections have stayed open for a while.

### CODE REVIEW

**Comment by Matt-MX** [comment]
Let us know how it goes!

**Comment by PseudoResonance** [comment]
This did resolve the main issue, however it still puts annoying errors in the logs every time the connection times out. From what I've read, you can either test the connection each time before use to ensure the errors won't show up, or switch to a connection pool like [HikariCP](https://github.com/brettwooldridge/HikariCP) for a more stable connection.

MySQL themselves [recommend against](https://dev.mysql.com/doc/connector-j/en/connector-j-connp-props-high-availability-and-clustering.html#cj-conn-prop_autoReconnect) using autoReconnect and say to properly check connection status instead.

**Comment by PseudoResonance** [comment]
I've migrated the original MySQL code to use HikariCP instead and it appears to work well. I've used it in the past without `autoReconnect=true` and never had this issue before, so I believe this will probably work long term.

**Comment by PseudoResonance** [comment]
I looked into it more, and it appears that you need to be able to fine tune the connection parameters, especially `maxLifetime` to match your server, so I added config options for them. Additionally, I read the MySQL driver sometimes caused some weird issues, so I tried adding support for the MariaDB driver as well. Finally, I migrated the SQLite to use HikariCP as well, given that it's already present anyways.

I can exclude some of those changes if you'd like though, or maybe drop one of the drivers or something. I quickly tested out MariaDB, MySQL and SQLite configs to make sure they all work too.

**Comment by Matt-MX** [comment]
Looks good to merge tbh, might revisit this project shortly just to refactor some code since it's pretty clunky and messy.

**Pull request merged**
